create table if not exists public.appointments (
 id bigint generated by default as identity primary key,
 vin text not null unique,
 plate text,
 model text,
 color text,
 salesperson text not null,
 service text not null check (service in ('wash_wax','coating')),
 delivery_date date not null,
 work_date date not null,
 start_time time not null,
 end_time time not null,
 resource_no integer not null,
 priority text not null check (priority in ('P1','P2','P3')),
 status text not null default 'scheduled' check (status in ('scheduled','in_progress','qc','completed','cancelled')),
 note text,
 created_at timestamptz default now(),
 updated_at timestamptz default now()
);
alter table public.appointments enable row level security;
create policy "public read" on public.appointments for select using (true);
create policy "public insert" on public.appointments for insert with check (true);
create policy "public update" on public.appointments for update using (true) with check (true);
